#use_frameworks!

platform :ios, '11.0'

target 'akara-ios_Example' do
  pod 'AkaraIOS', :path => '../'

  target 'akara-ios_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
